Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/11/2022
Var
// Seção de Declarações das variáveis 
a,b:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a<-2000
B<-10
escreva(a/b)

Fimalgoritmo